# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'try_twitter_login' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for try_twitter_login
    pod 'TwitterKit'

end
