# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'try-twitter-login-swifter' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for try-twitter-login-swifter
    pod 'Swifter', :git => 'https://github.com/mattdonnelly/Swifter.git'


end
