# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'try-swiftUI-weather' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for try-swiftUI-weather
  pod 'SwiftLint'

  target 'try-swiftUI-weatherTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'try-swiftUI-weatherUITests' do
    # Pods for testing
  end

end
